"""add value column to thread_tags

Revision ID: c7af282e1fd7
Revises: f36c5a44f4cb
Create Date: 2026-07-13 00:39:14.948109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7af282e1fd7'
down_revision: Union[str, None] = 'f36c5a44f4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'thread_tags',
        sa.Column('value', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('thread_tags', 'value', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_tags', 'value')
    # ### end Alembic commands ###
